### ISSUE TITLE
Decide on a Name

### ISSUE THREAD

**Issue by xgron** [xgron/GameSeeker#32]

**Comment by xgron** [comment]
Nima (Niclas och Martin). Låter bra med både svenskt och engelskt uttal och är ett periskt namn som betyder rättvisa.

Jugo. Låter bra med både svenskt och engelskt uttal och betyder nästan "jag spelar" på spanska och "dom" på esperanto.

Kachi. Betyder "att värdesätta" på japanska och är en onomatopoesi vi teoretiskt sätt skulle kunna använda i ljuddesignen ifall

//idéer från Martins håll!

**Comment by zgron** [comment]
Game Deck

**Comment by zgron** [comment]
Kachi is semi kanon!
